### ISSUE TITLE
Create NSA first draft model_digital version

### ISSUE THREAD

**Issue by BuiThiKhanhHoa** [BuiThiKhanhHoa/Nutrition-sensitive-Agriculture-Hanoi#1]
Make a digital version of it
[NSA_first draft model.pdf](https://github.com/BuiThiKhanhHoa/Nutrition-sensitive-Agriculture-Hanoi/files/12182483/NSA_first.draft.model.pdf)

**Comment by CWWhitney** [comment]
![Screenshot 2023-08-03 at 1 38 22 PM](https://github.com/BuiThiKhanhHoa/Nutrition-sensitive-Agriculture-Hanoi/assets/19190662/52aba99f-1ae6-4273-ad04-0796d67cecf5)

**Comment by CWWhitney** [comment]
Nice

On Jul 27, 2023, at 12:57, BuiThiKhanhHoa ***@***.***> wrote:


Make a digital version of it
NSA_first draft model.pdf <https://github.com/BuiThiKhanhHoa/Nutrition-sensitive-Agriculture-Hanoi/files/12182483/NSA_first.draft.model.pdf>
